# Generated by Django 2.0.3 on 2018-05-01 08:18

import common.middlewares.current_user
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('uid', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(max_length=500)),
                ('notes', models.TextField()),
                ('created_by', models.ForeignKey(default=common.middlewares.current_user.get_current_user, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_created_by', to=settings.AUTH_USER_MODEL)),
                ('handled_by', models.ForeignKey(default=common.middlewares.current_user.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_handled_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientAccountAddresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('address_type', models.CharField(blank=True, choices=[('contact', 'contact'), ('billing', 'billing'), ('shipping', 'shipping')], default='', max_length=20)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Address')),
                ('client_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='client_accounts.ClientAccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('uid', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(max_length=500)),
                ('business_type', models.CharField(max_length=500)),
                ('gstin', models.CharField(blank=True, default='', max_length=500)),
                ('company_email', models.EmailField(blank=True, default='', max_length=2000)),
                ('company_phone', models.CharField(blank=True, default='', max_length=2000)),
                ('notes', models.TextField()),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='common.Address')),
                ('created_by', models.ForeignKey(default=common.middlewares.current_user.get_current_user, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Legal Entity',
                'verbose_name_plural': 'Legal Entities',
            },
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='legal_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_accounts.LegalEntity'),
        ),
    ]
