# Generated by Django 2.0.3 on 2018-03-22 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('uid', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=500)),
                ('notes', models.TextField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('handled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientAccountAddresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('address_type', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Address')),
                ('client_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client_accounts.ClientAccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('designation', models.CharField(max_length=100)),
                ('notes', models.TextField()),
                ('client_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_accounts.ClientAccount')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LegalAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('uid', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=500)),
                ('business_type', models.CharField(max_length=500)),
                ('gstin', models.CharField(blank=True, default='', max_length=500)),
                ('company_email', models.EmailField(blank=True, default='', max_length=2000)),
                ('company_phone', models.CharField(blank=True, default='', max_length=2000)),
                ('notes', models.TextField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LegalAccountAddresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('address_type', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Address')),
                ('legal_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client_accounts.LegalAccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='legal_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_accounts.LegalAccount'),
        ),
    ]
