# Generated by Django 2.0.3 on 2018-03-25 18:54

import common.middlewares.current_user
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('client_accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LegalAccountAddresses',
            new_name='LegalEntityAddresses',
        ),
        migrations.AlterModelOptions(
            name='legalentity',
            options={'verbose_name': 'Legal Entity', 'verbose_name_plural': 'Legal Entities'},
        ),
        migrations.AlterField(
            model_name='clientaccount',
            name='created_by',
            field=models.ForeignKey(default=common.middlewares.current_user.get_current_user, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clientaccount',
            name='handled_by',
            field=models.ForeignKey(default=common.middlewares.current_user.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(default=common.middlewares.current_user.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='created_by',
            field=models.ForeignKey(default=common.middlewares.current_user.get_current_user, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='uid',
            field=models.CharField(editable=False, max_length=20),
        ),
    ]
