# Generated by Django 2.0.3 on 2018-05-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaccount',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
