# Generated by Django 2.0.3 on 2018-03-25 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('client_accounts', '0002_auto_20180325_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legalentityaddresses',
            name='address',
        ),
        migrations.RemoveField(
            model_name='legalentityaddresses',
            name='legal_account',
        ),
        migrations.AddField(
            model_name='legalentity',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Address'),
        ),
        migrations.DeleteModel(
            name='LegalEntityAddresses',
        ),
    ]
