# Generated by Django 2.0.3 on 2018-05-01 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_accounts', '0004_auto_20180501_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesstype',
            old_name='titlte',
            new_name='title',
        ),
    ]
