# Generated by Django 2.0.3 on 2018-03-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_accounts', '0004_auto_20180325_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaccount',
            name='uid',
            field=models.CharField(editable=False, max_length=20),
        ),
    ]
