# Generated by Django 2.0.3 on 2018-03-27 19:47

import common.middlewares.current_user
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_accounts', '0005_auto_20180327_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaccount',
            name='created_by',
            field=models.ForeignKey(default=common.middlewares.current_user.get_current_user, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clientaccount',
            name='handled_by',
            field=models.ForeignKey(default=common.middlewares.current_user.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_handled_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
