# Generated by Django 2.0.3 on 2018-05-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_accounts', '0005_auto_20180501_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesstype',
            name='title',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
