# Generated by Django 2.0.3 on 2018-04-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_accounts', '0006_auto_20180327_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaccountaddresses',
            name='address_type',
            field=models.CharField(blank=True, choices=[('contact', 'contact'), ('billing', 'billing'), ('shipping', 'shipping')], default='', max_length=20),
        ),
    ]
