# Generated by Django 2.0.3 on 2018-04-29 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_accounts', '0007_auto_20180408_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaccountaddresses',
            name='client_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='client_accounts.ClientAccount'),
        ),
    ]
