# Generated by Django 2.0.3 on 2018-05-01 08:18

import common.middlewares.current_user
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('uid', models.CharField(editable=False, max_length=20, unique=True)),
                ('client_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_accounts.ClientAccount')),
                ('contact', models.ForeignKey(default=common.middlewares.current_user.get_current_user, on_delete=django.db.models.deletion.CASCADE, related_name='lead_contact', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(default=common.middlewares.current_user.get_current_user, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_created_by', to=settings.AUTH_USER_MODEL)),
                ('designation', models.ForeignKey(default=common.middlewares.current_user.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lead_management.Designation')),
                ('handled_by', models.ForeignKey(default=common.middlewares.current_user.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_handled_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeadStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lead_management.LeadStage'),
        ),
    ]
