# Generated by Django 2.0.3 on 2018-04-01 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='client_account',
        ),
        migrations.AlterField(
            model_name='lead',
            name='contact',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='client_accounts.Contact'),
            preserve_default=False,
        ),
    ]
