# Generated by Django 2.0.3 on 2018-05-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
