# Generated by Django 2.0.3 on 2018-04-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0002_auto_20180401_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='stage',
            field=models.CharField(choices=[('identify', 'identify'), ('call', 'call'), ('prospect', 'prospect'), ('profile_sent', 'profile_sent'), ('supporter', 'supporter'), ('enquiry', 'enquiry'), ('appointment', 'appointment'), ('business', 'business')], max_length=20),
        ),
    ]
