# Generated by Django 2.0.3 on 2018-04-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0003_auto_20180408_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='stage',
            field=models.CharField(choices=[('identify', 'identify'), ('prospect', 'prospect'), ('supporter', 'supporter'), ('enquiry', 'enquiry'), ('business', 'business'), ('closed', 'closed')], max_length=20),
        ),
    ]
