# Generated by Django 2.0.3 on 2018-05-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0003_lead_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadstage',
            name='uid',
            field=models.CharField(default='', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='designation',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='leadstage',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
