# Generated by Django 2.0.3 on 2018-05-01 09:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_accounts', '0006_auto_20180501_0858'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lead_management', '0004_auto_20180501_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadstage',
            name='uid',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='lead',
            unique_together={('client_account', 'contact', 'handled_by')},
        ),
    ]
