# Generated by Django 2.0.3 on 2018-04-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0004_auto_20180424_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='uid',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
