# Generated by Django 2.0.3 on 2018-05-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0005_auto_20180501_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='has_been_called',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='has_been_sent_profile',
            field=models.BooleanField(default=False),
        ),
    ]
