# Generated by Django 2.0.3 on 2018-05-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_profile_salutation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salutation',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
