# Generated by Django 2.0.3 on 2018-05-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20180501_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_day',
        ),
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
